nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['^http://127.0.0.1:[0-9]+', '^http://localhost:[0-9]+']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
